"""Score a serving month with the production fare model and record predictions.

This is the real batch scoring job. Its output table is what a downstream
pricing system would consume, and it is the table Culprit queries when it needs
a dollar figure. Every number Culprit reports as money is computed here in SQL
against real rows, never generated by a language model.

Usage:  python pipeline/score_batch.py [--month 2025-06]
"""

from __future__ import annotations

import argparse
import json
import pickle
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
WAREHOUSE = HERE / "warehouse.duckdb"
ARTIFACTS = HERE / "artifacts"
TARGET = "total_amount"


def load_model(variant: str):
    with open(ARTIFACTS / f"{variant}_model.pkl", "rb") as fh:
        bundle = pickle.load(fh)
    return bundle["model"], bundle["features"]


def prepare(df: pd.DataFrame, features: list[str]) -> np.ndarray:
    frame = df.copy()
    if "is_vendor_helix" in features:
        frame["is_vendor_helix"] = (frame["vendor_id"] == 7).astype(int)
    return frame[features].to_numpy(dtype=np.float64)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--month", default="2025-06")
    args = ap.parse_args()

    con = duckdb.connect(str(WAREHOUSE))
    df = con.execute(
        "SELECT * FROM main_marts.fct_trip_features WHERE feed_month = ?", [args.month]
    ).df()
    print(f"scoring {len(df):,} real trips from {args.month}")

    prod_model, prod_features = load_model("production")
    ctrl_model, ctrl_features = load_model("control")

    df["predicted_total"] = prod_model.predict(prepare(df, prod_features))
    df["control_predicted_total"] = ctrl_model.predict(prepare(df, ctrl_features))
    df["abs_error"] = (df["predicted_total"] - df[TARGET]).abs()
    df["control_abs_error"] = (df["control_predicted_total"] - df[TARGET]).abs()

    out = df[
        [
            "pickup_at", "feed_month", "vendor_id", "trip_distance", "trip_minutes",
            "avg_speed_mph", "is_vendor_cmt", "is_vendor_curb", "is_vendor_myle",
            TARGET, "predicted_total", "abs_error", "control_predicted_total",
            "control_abs_error",
        ]
    ]
    con.execute("CREATE SCHEMA IF NOT EXISTS main_serving")
    con.register("out_df", out)
    con.execute(
        "CREATE OR REPLACE TABLE main_serving.fare_predictions AS SELECT * FROM out_df"
    )

    summary = con.execute(
        """
        SELECT
            vendor_id,
            COUNT(*)                                  AS trips,
            ROUND(AVG(abs_error), 4)                  AS production_mae,
            ROUND(AVG(control_abs_error), 4)          AS control_mae,
            ROUND(AVG(abs_error) - AVG(control_abs_error), 4) AS attributable_mae,
            ROUND(AVG(avg_speed_mph), 3)              AS avg_speed_feature,
            ROUND(AVG(is_vendor_cmt + is_vendor_curb + is_vendor_myle), 4) AS vendor_flag_sum
        FROM main_serving.fare_predictions
        GROUP BY 1 ORDER BY trips DESC
        """
    ).df()
    print("\n" + "=" * 92)
    print(f"PER-VENDOR RESULTS ON REAL {args.month} TRIPS")
    print("=" * 92)
    print(summary.to_string(index=False))

    impact = con.execute(
        """
        SELECT
            COUNT(*)                                                       AS affected_trips,
            ROUND(AVG(abs_error), 4)                                       AS production_mae,
            ROUND(AVG(control_abs_error), 4)                               AS control_mae,
            ROUND(AVG(abs_error) - AVG(control_abs_error), 4)              AS attributable_mae_per_trip,
            ROUND(SUM(abs_error - control_abs_error), 2)                   AS attributable_dollars,
            ROUND(SUM(total_amount), 2)                                    AS gross_fare_exposed
        FROM main_serving.fare_predictions
        WHERE vendor_id = 7
        """
    ).df()
    print("\n" + "=" * 92)
    print("ATTRIBUTABLE IMPACT (production minus control, vendor 7 only)")
    print("=" * 92)
    print(impact.to_string(index=False))

    row = impact.iloc[0].to_dict()
    row["month"] = args.month
    (ARTIFACTS / f"impact_{args.month}.json").write_text(
        json.dumps({k: (float(v) if isinstance(v, (int, float, np.floating)) else v)
                    for k, v in row.items()}, indent=2)
    )
    con.close()


if __name__ == "__main__":
    main()
