name: nyc_fares
version: "1.0.0"
config-version: 2

profile: nyc_fares

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  nyc_fares:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
