"""Regenerate everything in examples/ from the live warehouse and DataHub instance.

The hackathon asks for sample outputs so judges can evaluate quality without
running the code. Everything here is produced from the real run, so it can be
regenerated and diffed rather than being hand-written prose that drifts from
what the system actually does.

Usage:  python scripts/generate_examples.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
EXAMPLES = ROOT / "examples"

from culprit import datahub_graph as dg  # noqa: E402
from culprit import warehouse as wh  # noqa: E402


def write_json(name: str, payload: object) -> None:
    (EXAMPLES / name).write_text(json.dumps(payload, indent=2, default=str))
    print(f"  wrote examples/{name}")


def main() -> None:
    EXAMPLES.mkdir(exist_ok=True)

    # 1. The semantic change, as found in the real feed.
    profile = wh.profile_column_over_time("raw.yellow_trips", "vendor_id")
    write_json("01_semantic_change_detected.json", profile)

    # 2. The full monitor sweep, at both layers, including the metrics that fire.
    monitors = wh.check_standard_monitors("raw.yellow_trips", "vendor_id")
    feature_monitors = wh.check_standard_monitors(
        "main_marts.fct_trip_features", "avg_speed_mph"
    )
    write_json(
        "02_monitor_sweep.json",
        {"source_column": monitors, "derived_feature": feature_monitors},
    )
    stale = EXAMPLES / "02_monitors_all_green.json"
    if stale.exists():
        stale.unlink()
        print("  removed examples/02_monitors_all_green.json (name was an overclaim)")

    # 3. Per-segment feature behaviour.
    drift = wh.feature_drift_report("vendor_id")
    write_json("03_feature_behaviour_by_vendor.json", drift)

    # 4. The measured impact, both estimators.
    impact = wh.measure_attributable_error("vendor_id", 7)
    write_json("04_measured_impact.json", impact)

    # 5. Second, smaller real finding, reported rather than suppressed.
    impact6 = wh.measure_attributable_error("vendor_id", 6)
    write_json("05_secondary_finding_vendor6.json", impact6)

    # 6. The ML lineage Culprit contributed to the graph.
    try:
        model = dg.get_model_context(
            "urn:li:mlModel:(urn:li:dataPlatform:duckdb,nyc_fare_predictor,PROD)"
        )
        features = [dg.get_feature_context(u) for u in model["features"]]
        write_json("06_ml_lineage_in_datahub.json", {"model": model, "features": features})
    except Exception as exc:  # noqa: BLE001
        print(f"  skipped ML lineage export (DataHub not reachable): {exc}")

    # 7. A human-readable summary table.
    lines = [
        "# Culprit: measured results",
        "",
        "Generated by `python scripts/generate_examples.py` from the live warehouse.",
        "All figures are computed in SQL against real NYC TLC trip records.",
        "",
        "## The semantic change in the real TLC feed",
        "",
        "| feed month | distinct vendor codes | new value |",
        "|---|---|---|",
    ]
    new_by_month = {n["first_seen_month"]: n for n in profile.get("new_values_appeared", [])}
    for month, values in profile.get("values_by_month", {}).items():
        new = new_by_month.get(month)
        note = f"**{new['value']}** ({new['rows_in_first_month']:,} rows)" if new else ""
        lines.append(f"| {month} | {', '.join(values)} | {note} |")

    lines += [
        "",
        "## What conventional monitoring saw",
        "",
        f"- dtype: `{monitors['dtype']}`, stable across every month",
        f"- max null percentage: {monitors['max_null_pct']}%",
        f"- row volume swing: {monitors['row_volume_swing_pct']}%",
        "",
        "The metrics that fire are included. Testing only the ones that stay",
        "silent would be picking the scoreboard.",
        "",
        "| monitor | on `vendor_id` | on `avg_speed_mph` |",
        "|---|---|---|",
    ]
    for key, value in monitors.items():
        if key.endswith("would_fire"):
            other = feature_monitors.get(key)
            lines.append(
                f"| {key.replace('_would_fire', '')} "
                f"| {'FIRES' if value else 'silent'} "
                f"| {'FIRES' if other else 'silent'} |"
            )

    zc = feature_monitors.get("zero_count_first_change")
    uc = monitors.get("unique_count_first_change")
    lines += [
        "",
        "### The two that fire, and why neither is actionable",
        "",
        f"- `unique_count` on `vendor_id` goes {uc['from']} to {uc['to']} in "
        f"{uc['month']}. That is the same integer the max value already shows, "
        "and it names no model." if uc else "",
        "",
        "- `zero_count` on `avg_speed_mph` climbs because the `coalesce` that "
        "dodges the null check lands the corruption in the zero count instead:",
        "",
        "| feed month | zero rows | share |",
        "|---|---:|---:|",
    ]
    for r in feature_monitors["per_month"]:
        share = 100.0 * r["zero_count"] / r["row_volume"]
        lines.append(
            f"| {r['feed_month']} | {int(r['zero_count']):,} | {share:.4f}% |"
        )
    lines += [
        "",
        f"In {zc['month']}, the month the defect entered production, that is "
        f"{int(zc['to']):,} rows, {zc['share_of_rows_pct']}% of the table, against a "
        "baseline that already swings between 33 and 43. It is indistinguishable "
        "from noise. The first month it is unmissable is 2025-03, a quarter after "
        "the model started serving the new vendor wrong." if zc else "",
        "",
        "And when it does fire it says *some speeds are zero*. It does not name",
        "`nyc_fare_predictor`, does not name the retrain that baked it in, and does",
        "not produce a dollar figure. Detection was never the hard part.",
        "Attribution is.",
    ]

    lines += [
        "",
        "## Model behaviour by vendor, real 2025-06",
        "",
        "Inputs are discovered from the schema, not named in the query. An input",
        "with zero variance inside one segment is flagged as degenerate there.",
        "",
        "| vendor | trips | production MAE | control MAE | degenerate inputs |",
        "|---|---:|---:|---:|---|",
    ]
    for r in drift["segments"]:
        degenerate = ", ".join(f"`{c}`" for c in r["degenerate_in_segment"]) or "none"
        lines.append(
            f"| {r['segment']} | {r['rows']:,} | ${r['production_mae']} "
            f"| ${r['control_mae']} | {degenerate} |"
        )
    lines += [
        "",
        "Every segment shows its own vendor one-hots as degenerate, which is",
        "expected: within a single vendor those flags are constant by construction.",
        "Vendor 7 is the only segment where `trip_minutes` and `avg_speed_mph`",
        "collapse as well. That difference is the fingerprint.",
    ]

    lines += [
        "",
        "## Measured impact on vendor 7",
        "",
        f"- affected trips: **{impact['affected_rows']:,}**",
        f"- production MAE: ${impact['production_mae']}",
        f"- control MAE: ${impact['control_mae']}",
        f"- naive attributable: ${impact['attributable_dollars']:,.2f}",
        f"- control's unearned advantage, measured on {impact['baseline_rows']:,} "
        f"unaffected rows: ${impact['baseline_control_lift_per_row']}/row",
        f"- **difference-in-differences attributable: "
        f"${impact['did_attributable_dollars']:,.2f}**",
        f"- gross fare exposed: ${impact['gross_amount_exposed']:,.2f}",
        "",
        "The difference-in-differences figure is the headline. It is the stricter of",
        "the two estimators because it removes the control model's advantage from",
        "having been trained on more and fresher data.",
    ]
    (EXAMPLES / "RESULTS.md").write_text("\n".join(lines))
    print("  wrote examples/RESULTS.md")


if __name__ == "__main__":
    main()
