"""Regenerate everything in examples/ from the live warehouse and DataHub instance.

The hackathon asks for sample outputs so judges can evaluate quality without
running the code. Everything here is produced from the real run, so it can be
regenerated and diffed rather than being hand-written prose that drifts from
what the system actually does.

Usage:  python scripts/generate_examples.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
EXAMPLES = ROOT / "examples"

from culprit import datahub_graph as dg  # noqa: E402
from culprit import warehouse as wh  # noqa: E402


def write_json(name: str, payload: object) -> None:
    (EXAMPLES / name).write_text(json.dumps(payload, indent=2, default=str))
    print(f"  wrote examples/{name}")


def main() -> None:
    EXAMPLES.mkdir(exist_ok=True)

    # 1. The semantic change, as found in the real feed.
    profile = wh.profile_column_over_time("raw.yellow_trips", "vendor_id")
    write_json("01_semantic_change_detected.json", profile)

    # 2. What conventional monitoring would have seen.
    monitors = wh.check_standard_monitors("raw.yellow_trips", "vendor_id")
    write_json("02_monitors_all_green.json", monitors)

    # 3. Per-segment feature behaviour.
    drift = wh.feature_drift_report("vendor_id")
    write_json("03_feature_behaviour_by_vendor.json", drift)

    # 4. The measured impact, both estimators.
    impact = wh.measure_attributable_error("vendor_id", 7)
    write_json("04_measured_impact.json", impact)

    # 5. Second, smaller real finding, reported rather than suppressed.
    impact6 = wh.measure_attributable_error("vendor_id", 6)
    write_json("05_secondary_finding_vendor6.json", impact6)

    # 6. The ML lineage Culprit contributed to the graph.
    try:
        model = dg.get_model_context(
            "urn:li:mlModel:(urn:li:dataPlatform:duckdb,nyc_fare_predictor,PROD)"
        )
        features = [dg.get_feature_context(u) for u in model["features"]]
        write_json("06_ml_lineage_in_datahub.json", {"model": model, "features": features})
    except Exception as exc:  # noqa: BLE001
        print(f"  skipped ML lineage export (DataHub not reachable): {exc}")

    # 7. A human-readable summary table.
    lines = [
        "# Culprit: measured results",
        "",
        "Generated by `python scripts/generate_examples.py` from the live warehouse.",
        "All figures are computed in SQL against real NYC TLC trip records.",
        "",
        "## The semantic change in the real TLC feed",
        "",
        "| feed month | distinct vendor codes | new value |",
        "|---|---|---|",
    ]
    new_by_month = {n["first_seen_month"]: n for n in profile.get("new_values_appeared", [])}
    for month, values in profile.get("values_by_month", {}).items():
        new = new_by_month.get(month)
        note = f"**{new['value']}** ({new['rows_in_first_month']:,} rows)" if new else ""
        lines.append(f"| {month} | {', '.join(values)} | {note} |")

    lines += [
        "",
        "## What conventional monitoring saw",
        "",
        f"- dtype: `{monitors['dtype']}`, stable across every month",
        f"- max null percentage: {monitors['max_null_pct']}%",
        f"- row volume swing: {monitors['row_volume_swing_pct']}%",
        "",
        "| monitor | would fire |",
        "|---|---|",
    ]
    for key, value in monitors.items():
        if key.endswith("would_fire"):
            lines.append(f"| {key.replace('_would_fire', '')} | {'YES' if value else 'no'} |")

    lines += [
        "",
        "## Model behaviour by vendor, real 2025-06",
        "",
        "| vendor | trips | avg_speed_mph feature | vendor one-hot sum | production MAE |",
        "|---|---:|---:|---:|---:|",
    ]
    for r in drift:
        lines.append(
            f"| {r['segment']} | {r['trips']:,} | {r['avg_speed_mph']} | "
            f"{r['vendor_onehot_sum']} | ${r['production_mae']} |"
        )

    lines += [
        "",
        "## Measured impact on vendor 7",
        "",
        f"- affected trips: **{impact['affected_rows']:,}**",
        f"- production MAE: ${impact['production_mae']}",
        f"- control MAE: ${impact['control_mae']}",
        f"- naive attributable: ${impact['attributable_dollars']:,.2f}",
        f"- control's unearned advantage, measured on {impact['baseline_rows']:,} "
        f"unaffected rows: ${impact['baseline_control_lift_per_row']}/row",
        f"- **difference-in-differences attributable: "
        f"${impact['did_attributable_dollars']:,.2f}**",
        f"- gross fare exposed: ${impact['gross_amount_exposed']:,.2f}",
        "",
        "The difference-in-differences figure is the headline. It is the stricter of",
        "the two estimators because it removes the control model's advantage from",
        "having been trained on more and fresher data.",
    ]
    (EXAMPLES / "RESULTS.md").write_text("\n".join(lines))
    print("  wrote examples/RESULTS.md")


if __name__ == "__main__":
    main()
